version: 2.1

orbs:
  python: circleci/python@0.3.2

jobs:
  build:
    executor: python/default
    steps:
      - run:
          name: Clone repo
          command: git clone https://github.com/martino-vic/koeblergothic.git
      - run:
          name: Clone reference catalogues (takes 1min15s) & loanpy
          command: |
            mkdir concepticon
            cd concepticon
            git clone https://github.com/concepticon/concepticon-data.git
            cd ..
            git clone https://github.com/glottolog/glottolog.git
            git clone https://github.com/cldf-clts/clts.git
            git clone https://github.com/martino-vic/loanpy.git
            url="https://raw.githubusercontent.com/martino-vic/ronataswestoldturkic/main/loanpy/WOT2EAHsc.json"
            curl -s -L "$url" -o koeblergothic/etc/WOT2EAHsc.json
      - run:
          name: install commands & download spacy word vector model
          command: |
            pip install -e koeblergothic
            pip install -e loanpy
            python3 -m spacy download de_core_news_lg
      - run:
          name: Preprocess: create etc/gothic.tsv and etc/concepts.tsv
          command: |
            cd koeblergothic
            cldfbench koeblergothic.txt2tsv
            cldfbench koeblergothic.map2concepts
      - run:
          name: run lexibank script
          command: >
            cd koeblergothic &&
            cldfbench lexibank.makecldf cldfbench_koeblergothic.py
            --concepticon-version=v2.5.0
            --glottolog-version=v4.5
            --clts-version=v2.2.0
            --concepticon=../concepticon/concepticon-data
            --glottolog=../glottolog
            --clts=../clts
      - run:
          name: Install pytest-cldf & check if dataset is CLDF conform
          command: |
            pip install pytest-cldf
            cd koeblergothic
            pytest --cldf-metadata=cldf/cldf-metadata.json test.py
      - run:
          name: Update readme
          command: >
            cd koeblergothic &&
            cldfbench koeblergothic.update_readme
      - run:
          name: Postprocess: create orthographic profile, add stats to readme
          command: |
            cd koeblergothic
            cldfbench koeblergothic.makeortho
            cldfbench koeblergothic.update_readme

workflows:
  main:
    jobs:
      - build
